"""A dependency-free PDF writer for the Part 9 report download.

Why hand-rolled: the deployment contract for this project is a small, audited
dependency set, and a report PDF needs only text, lines and pages. Every byte
emitted here is generated by this file — no template engine, no network, no
font embedding (standard PDF base-14 fonts only), no external input beyond the
already-stored result document.

The one-viewport rule applies to the *interactive* app; the exported document
may freely span pages (rule 25). Text is escaped for the PDF string syntax
(rule 7 — the renderer is XSS-irrelevant, but injection-safe all the same).
"""

from __future__ import annotations

from typing import Any, Iterable

PAGE_W = 595.28  # A4 points
PAGE_H = 841.89
MARGIN = 48.0
CONTENT_W = PAGE_W - 2 * MARGIN

_FONT_REGULAR = "F1"
_FONT_BOLD = "F2"


def _esc(text: Any) -> str:
    """Escape text for a PDF literal string (WinAnsi-safe fallback)."""
    if text is None:
        return ""
    s = str(text)
    # WinAnsi cannot render every character; replace the known offenders so the
    # stream stays valid. Content stays truthful — arrows and symbols become
    # their ASCII meaning.
    replacements = {
        "\u2192": "->",
        "\u2190": "<-",
        "\u2014": "-",
        "\u2013": "-",
        "\u2018": "'",
        "\u2019": "'",
        "\u201c": '"',
        "\u201d": '"',
        "\u2026": "...",
        "\u00a0": " ",
    }
    for old, new in replacements.items():
        s = s.replace(old, new)
    try:
        s.encode("cp1252")
    except UnicodeEncodeError:
        s = s.encode("cp1252", "replace").decode("cp1252")
    return s.replace("\\", "\\\\").replace("(", "\\(").replace(")", "\\)")


class _Page:
    def __init__(self) -> None:
        self.ops: list[str] = []

    def text(self, x: float, y: float, size: float, font: str, s: str) -> None:
        self.ops.append(
            f"BT /{font} {size:.1f} Tf {x:.2f} {y:.2f} Td ({_esc(s)}) Tj ET"
        )

    def line(self, x1: float, y1: float, x2: float, y2: float) -> None:
        self.ops.append(f"{x1:.2f} {y1:.2f} m {x2:.2f} {y2:.2f} l S")

    def render(self) -> str:
        return "\n".join(self.ops)


class PdfBuilder:
    """Accumulates flowed text and emits a valid multi-page PDF document."""

    def __init__(self, title: str) -> None:
        self._title = title
        self._pages: list[_Page] = []
        self._page = self._new_page()
        self._y = PAGE_H - MARGIN

    def _new_page(self) -> _Page:
        return _Page()

    # ------------------------------------------------------------- flowing

    def _ensure(self, needed: float) -> None:
        if self._y - needed < MARGIN:
            self.page_break()

    def page_break(self) -> None:
        self._pages.append(self._page)
        self._page = self._new_page()
        self._y = PAGE_H - MARGIN

    def heading(self, text: str, *, size: float = 14.0) -> None:
        self._ensure(size + 14)
        self._y -= size + 6
        self._page.text(MARGIN, self._y, size, _FONT_BOLD, text)
        self._y -= 6

    def rule(self) -> None:
        self._ensure(10)
        self._y -= 4
        self._page.line(MARGIN, self._y, PAGE_W - MARGIN, self._y)
        self._y -= 6

    def text(self, s: str, *, size: float = 10.0, bold: bool = False, indent: float = 0.0) -> None:
        """One paragraph, word-wrapped to the content width."""
        wrapped = _wrap(s, CONTENT_W - indent, size)
        for line in wrapped:
            self._ensure(size + 4)
            self._y -= size + 3
            self._page.text(MARGIN + indent, self._y, size, _FONT_BOLD if bold else _FONT_REGULAR, line)

    def key_value(self, key: str, value: str, *, indent: float = 8.0) -> None:
        self.text(f"{key}: {value}", indent=indent)

    def bullet(self, s: str, *, indent: float = 14.0) -> None:
        self.text(f"- {s}", indent=indent)

    # ------------------------------------------------------------- emitting

    def build(self) -> bytes:
        """Serialize the accumulated pages into PDF bytes."""
        if self._page.ops:
            self._pages.append(self._page)
        pages = self._pages or [_Page()]

        objects: list[bytes] = []

        def add(body: bytes) -> int:
            objects.append(body)
            return len(objects)  # 1-based object number

        # Placeholder order: catalog(1), pages(2), then per page: page + content,
        # then fonts. Resolve numbers as we go.
        font_regular_num = len(objects) + 1  # filled after the loop below
        page_ids: list[int] = []
        content_ids: list[int] = []

        # Reserve catalog and pages as objects 1 and 2.
        add(b"")  # 1 catalog placeholder
        add(b"")  # 2 pages placeholder

        for page in pages:
            stream = page.render().encode("cp1252", "replace")
            content_id = add(
                b"<< /Length " + str(len(stream)).encode() + b" >>\nstream\n" + stream + b"\nendstream"
            )
            content_ids.append(content_id)
            page_id = add(
                (
                    f"<< /Type /Page /Parent 2 0 R /MediaBox [0 0 {PAGE_W:.2f} {PAGE_H:.2f}] "
                    f"/Resources << /Font << /{_FONT_REGULAR} %d 0 R /{_FONT_BOLD} %d 0 R >> >> "
                    f"/Contents {content_id} 0 R >>"
                ).encode()
                % (
                    len(objects) + 1,  # regular font object (added next)
                    len(objects) + 2,  # bold font object
                )
            )
            page_ids.append(page_id)

        font_regular_id = add(b"<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>")
        font_bold_id = add(b"<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica-Bold >>")

        kids = " ".join(f"{pid} 0 R" for pid in page_ids)
        objects[1] = (
            f"<< /Type /Pages /Count {len(page_ids)} /Kids [{kids}] >>".encode()
        )
        objects[0] = b"<< /Type /Catalog /Pages 2 0 R >>"

        # Rewrite each page object with the now-known font ids.
        for index, page_id in enumerate(page_ids):
            content_id = content_ids[index]
            objects[page_id - 1] = (
                f"<< /Type /Page /Parent 2 0 R /MediaBox [0 0 {PAGE_W:.2f} {PAGE_H:.2f}] "
                f"/Resources << /Font << /{_FONT_REGULAR} {font_regular_id} 0 R "
                f"/{_FONT_BOLD} {font_bold_id} 0 R >> >> /Contents {content_id} 0 R >>"
            ).encode()

        del font_regular_num  # unused legacy placeholder

        out = bytearray(b"%PDF-1.4\n%\xe2\xe3\xcf\xd3\n")
        offsets: list[int] = []
        for number, body in enumerate(objects, start=1):
            offsets.append(len(out))
            out += f"{number} 0 obj\n".encode()
            out += body
            out += b"\nendobj\n"

        xref_pos = len(out)
        out += f"xref\n0 {len(objects) + 1}\n".encode()
        out += b"0000000000 65535 f \n"
        for offset in offsets:
            out += f"{offset:010d} 00000 n \n".encode()
        out += (
            f"trailer\n<< /Size {len(objects) + 1} /Root 1 0 R >>\n"
            f"startxref\n{xref_pos}\n%%EOF\n"
        ).encode()
        return bytes(out)


def _wrap(text: str, width: float, size: float) -> list[str]:
    """Greedy word wrap at ~0.5*size per character (Helvetica average)."""
    if not text:
        return [""]
    char_w = size * 0.5
    max_chars = max(8, int(width / char_w))
    lines: list[str] = []
    for paragraph in str(text).split("\n"):
        current = ""
        for word in paragraph.split(" "):
            candidate = f"{current} {word}".strip()
            if len(candidate) <= max_chars:
                current = candidate
            else:
                if current:
                    lines.append(current)
                current = word[:max_chars]
        lines.append(current)
    return lines or [""]


# ---------------------------------------------------------------------------
# Report assembly
# ---------------------------------------------------------------------------


def render_report_pdf(document: dict) -> bytes:
    """Render the stored analysis document as a multi-page PDF report."""
    pdf = PdfBuilder(title="SafeFlux engineering report")
    goal = document.get("goal") or "(no goal recorded)"
    pdf.heading("SafeFlux engineering report", size=18)
    pdf.text(goal, size=11, bold=True)
    pdf.rule()

    interpreted = document.get("interpreted_change") or {}
    pdf.heading("Interpreted change")
    pdf.key_value("Direction", str(interpreted.get("direction") or "not stated"))
    pdf.key_value("Magnitude", str(interpreted.get("magnitude") or "not stated"))
    pdf.key_value(
        "Variables",
        ", ".join(interpreted.get("variables") or []) or "default search set",
    )

    original = document.get("original") or {}
    counts = original.get("counts") or {}
    pdf.heading("Overview")
    pdf.key_value("Status", str(document.get("status") or original.get("status") or ""))
    pdf.key_value("Scenarios evaluated", str(counts.get("scenarios", 0)))
    pdf.key_value("Failing", str(counts.get("failing", 0)))
    pdf.key_value("Violations", str(counts.get("violation", 0)))
    pdf.key_value("Safeguard activations", str(counts.get("safeguard_activated", 0)))

    pdf.heading("Scenarios")
    for case in (original.get("cases") or [])[:40]:
        peaks = case.get("peaks") or {}
        pdf.bullet(
            f"{case.get('label') or case.get('key')}: status={case.get('status')}, "
            f"peak T={peaks.get('temperature_c')}, peak P={peaks.get('pressure_bar')}, "
            f"peak level={peaks.get('level_pct')}"
        )
    if len(original.get("cases") or []) > 40:
        pdf.text("(remaining scenarios omitted from the PDF; the app shows all)", size=9)

    pdf.heading("Failures")
    failures = document.get("failures") or []
    if not failures:
        pdf.text(NO_UNSAFE_DETECTED_SENTENCE)
    for failure in failures[:20]:
        peaks = failure.get("peaks") or {}
        pdf.text(failure.get("label") or str(failure.get("key")), bold=True)
        pdf.key_value("Status", str(failure.get("status")), indent=14)
        pdf.key_value(
            "Peaks",
            f"T={peaks.get('temperature_c')} P={peaks.get('pressure_bar')} L={peaks.get('level_pct')}",
            indent=14,
        )

    pdf.heading("Counterfactuals")
    for row in document.get("counterfactuals") or []:
        pdf.text(f"{row.get('label')} ({row.get('variable')} -> {row.get('value')})", bold=True)
        pdf.key_value("Resulting status", str(row.get("status")), indent=14)
        pdf.key_value("Improved", str(row.get("improved")), indent=14)

    pdf.heading("Safeguards")
    safeguards = (document.get("safeguards") or {}).get("timings") or []
    pdf.text(SAFEGUARD_NOTE_SENTENCE, size=9)
    for timing in safeguards:
        pdf.bullet(
            f"{timing.get('safeguard')}: trigger={timing.get('trigger_time_s')}s, "
            f"response={timing.get('response_time_s')}s, "
            f"violation={timing.get('violation_time_s')}s, prevented={timing.get('prevented')}"
        )

    pdf.heading("Evidence")
    pdf.text(EVIDENCE_SENTENCE, size=9)
    pdf.text(ANALYSIS_DISCLAIMER_SENTENCE, size=9)

    ai = document.get("ai_explanation") or {}
    if isinstance(ai, dict) and ai.get("text"):
        pdf.heading("AI explanation")
        pdf.text(str(ai.get("text")), size=9)
        pdf.text(AI_SEPARATION_SENTENCE, size=9)

    return pdf.build()


NO_UNSAFE_DETECTED_SENTENCE = (
    "No unsafe condition was detected within the tested simulation scenarios."
)
SAFEGUARD_NOTE_SENTENCE = (
    "Times describe the simulated response of the modelled safeguard, not the "
    "behaviour of a real plant."
)
EVIDENCE_SENTENCE = (
    "Every value in this report comes from the deterministic simulator and the "
    "configured safety limits; nothing is estimated."
)
ANALYSIS_DISCLAIMER_SENTENCE = (
    "SafeFlux explores simulated scenarios only; it never actuates real equipment "
    "and never guarantees a real plant is safe."
)
AI_SEPARATION_SENTENCE = (
    "The section above is an AI-generated explanation of the evidence. It is not "
    "simulation evidence and carries no verdict."
)


__all__ = ["PdfBuilder", "render_report_pdf"]
